### ISSUE TITLE
Miscellaneous questions

### ISSUE THREAD

**Issue by fconlon** [opensocsysarch/CoreGenPortal#101]
Thread for miscellaneous questions that may not necessarily belong on other issues

**Comment by fconlon** [comment]
@jleidel How is the syntax being used for Pseudo Insts? It's not showing at all in the PInst info window. Trying to set a syntax on a Psuedo Inst that corresponds to an Inst with no IF (since I'm allowing IF to be null in the info window) ended up being the root cause of the seg faults when modifying Instructions.

**Comment by jleidel** [comment]
The syntax sets the mnemonics for the generated compiler/assembler.  This is effectively how you “type” an instruction in the assembly language.

**Comment by fconlon** [comment]
Is there any reason for the syntax to be uneditable in the UI? I'm going to work on the tutorial this morning, but afterwards I can go through and look for all the node fields that are inaccessible from the UI and make issues to add them in. I can list the ones I find here and you can let me know which ones the UI needs to make editable and which ones I can leave out. I need to work on plugins and IFs as well.

**Comment by fconlon** [comment]
I'm creating a backlog of issues this morning. Would it be worthwhile to consider using a tool such as Asana or Jira for tracking backlogs and issues?

**Comment by fconlon** [comment]
Edit: It looks like Github might already have this built in https://help.github.com/en/articles/about-project-boards . I can look into setting up a board if you think it would help facilitate project management.

**Comment by jleidel** [comment]
I would say go with the project boards functionality
