### ISSUE TITLE
Rebase uifacilitation to devel and run tests

### ISSUE THREAD

**Issue by fconlon** [opensocsysarch/CoreGenPortal#102]

**Comment by fconlon** [comment]
compiling tests just failed at 64% with this message 

collect2: error: ld returned 1 exit status
test/DAG/DOT/CMakeFiles/dot_test_29.dir/build.make:112: recipe for target '../test/DAG/DOT/testBin/dot_test_29' failed
make[2]: *** [../test/DAG/DOT/testBin/dot_test_29] Error 1
CMakeFiles/Makefile2:13733: recipe for target 'test/DAG/DOT/CMakeFiles/dot_test_29.dir/all' failed
make[1]: *** [test/DAG/DOT/CMakeFiles/dot_test_29.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fconlon** [comment]
@jleidel I got all the tests to compile. I have everything rebased into devel on my local and all the tests pass. It's ready to push unless you want me to hold off. I'm going to go to bed for the night though.

**Comment by jleidel** [comment]
> @jleidel I got all the tests to compile. I have everything rebased into devel on my local and all the tests pass. It's ready to push unless you want me to hold off. I'm going to go to bed for the night though.

Feel free to push

**Comment by fconlon** [comment]
Completed by CoreGen Commit https://github.com/opensocsysarch/CoreGen/commit/4eb81810407274b29f23182d6de7744a2ba9a5eb
