### ISSUE TITLE
Connect Project Menu and Toolbar Save Buttons to Handlers

### ISSUE THREAD

**Issue by fconlon** [opensocsysarch/CoreGenPortal#104]
- [ ] Criteria 1

### Criteria 1
**Given:**
- A project is open in CoreGen Portal

**When:**
- The user clicks the save tool bar or project menu option

**Then:**
- All open files in the project should be saved

**Comment by fconlon** [comment]
@jleidel You added save functionality in commit 6f0b07602eea59afee886a105d55d4610c27da5a to work Issue #21. This save was generally what I had in mind for this issue. If there's a save file function already it could make sense to have a save all that would save all open panes instead. Would you like me to do that or take out the "Save" option and just hook the save file function up to the toolbar and then mark this as done?

**Comment by jleidel** [comment]
passed all devel tests
