### ISSUE TITLE
Connect Project Menu and Toolbar SaveAs Buttons to Handlers

### ISSUE THREAD

**Issue by fconlon** [opensocsysarch/CoreGenPortal#105]
- [ ] Criteria 1

### Criteria 1
**Given:**
- A project is open in CoreGen Portal

**When:**
- The user clicks the saveas tool bar or project menu option

**Then:**
- A save as dialogue should be displayed

**Comment by fconlon** [comment]
@jleidel I have a similar question here to the one that I had on #104. Would you like me to implement this to save all project files in a project or just the currently focused file?

**Comment by jleidel** [comment]
> @jleidel I have a similar question here to the one that I had on #104. Would you like me to implement this to save all project files in a project or just the currently focused file?

Save all the files into a new project.  This should basically create a new project directory and copy all the project files there

**Comment by jleidel** [comment]
fix in 18ae244

**Comment by jleidel** [comment]
passed all devel tests
