### ISSUE TITLE
Refactor Delete Node Functionality

### ISSUE THREAD

**Issue by fconlon** [opensocsysarch/CoreGenPortal#106]
As is the delete node functionality will save correctly when the project is closed but doesn't properly delete dependencies in the IR editor. This was due trouble with writeyaml when I originally wrote the functionality. Now that I know what the writeyaml issue was, I need to refactor the functionality to display the correct IR in the IR editor pane.

**Comment by jleidel** [comment]
this appears to be complete and functional
