### ISSUE TITLE
Change action buttons from "Save" and "Okay" -> "Save" and "Cancel" 

### ISSUE THREAD

**Issue by rkabrick** [opensocsysarch/CoreGenPortal#136]
I feel as though it'd be more intuitive for users to see buttons that say "Save" and "Cancel" across the GUI. "Okay" sounds analogous to "Save" while actually discarding the changes/edits a user makes

**Comment by jleidel** [comment]
I definitely agree.  This should be a relatively straightforward update, but great for usability

**Comment by jleidel** [comment]
passed all devel tests
