### ISSUE TITLE
Failure to read in input yaml file results in odd behavior

### ISSUE THREAD

**Issue by rkabrick** [opensocsysarch/CoreGenPortal#140]
If the input file is failed to be read into the portal it does not prompt the user to either try again or input another file. Consequently, it treats the file that prompted the error as a legitimate file and lets users add nodes to the corrupt file. An example of the strange behavior is as follows:

1) Read in corrupt file
2) Logpane gives error message 
3) If user goes to add, say a cache, inputting 1 in the integer fields throws an error to the log pane saying "1 is not a valid integer"

**Comment by jleidel** [comment]
on my version of the code, the application throws a segmentation fault on stage 3.  debugging further

**Comment by jleidel** [comment]
passed all devel tests
