### ISSUE TITLE
Complete Cache Edit Window Sad Path

### ISSUE THREAD

**Issue by fconlon** [opensocsysarch/CoreGenPortal#31]
- [x] Criteria 1
- [x] Criteria 2
- [x] Criteria 3
- [x] Criteria 4
- [x] Criteria 5

### Criteria 1
**Given:**
* The Cache edit window is open
* The user has entered an invalid name into the Cache name Box

**When:**
* The user clicks save

**Then:**
* An error message is displayed in the Log Pane
* The Cache Edit window remains open
* The Cache Name label is highlighted red

### Criteria 2
**Given:**
* The Cache edit window is open
* The user has entered a non-integer into the cache sets box

**When:**
* The user clicks save

**Then:**
* An error message is displayed in the Log Pane
* The Cache Edit window remains open
* The Sets label is highlighted red

### Criteria 3
**Given:**
* The Cache edit window is open
* The user has entered a non-integer into the cache ways box

**When:**
* The user clicks save

**Then:**
* An error message is displayed in the Log Pane
* The Cache Edit window remains open
* The Ways label is highlighted red

### Criteria 4
**Given:**
* The Cache edit window is open
* The user has entered an invalid cache into the Child Cache box

**When:**
* The user clicks save

**Then:**
* An error message is displayed in the Log Pane
* The Cache Edit window remains open
* The Child Cache label is highlighted red
* The entered cache is not added as a child

### Criteria 5
**Given:**
* The Cache edit window is open
* The user has entered a cache that creates a cycle into the Child Cache box

**When:**
* The user clicks save

**Then:**
* An error message is displayed in the Log Pane
* The Cache Edit window remains open
* The Parent Name label is highlighted red
* The Entered cache is not added as a Parent

**Comment by fconlon** [comment]
Noticed that child cache is not the same pointer as the cache that is returned by Getting cache by name. Is there a reason for that?

**Comment by jleidel** [comment]
It depends on what you're trying to do with it and how the cache is configured.

**Comment by jleidel** [comment]
I would suggest comparing the names rather than the raw pointers.  The names are required to be kept unique

**Comment by fconlon** [comment]
I ended up comparing names. Now I'm having an issue where under very specific, but not unreasonable conditions, the child cache isn't being added. If the user tries to add an invalid or cycle cache as a child then adds a valid cache it won't add the cache. I'm gonna spend about 30 more min on it and if I can't figure it out then I'm going to close this issue and open a bug issue. At the moment though criteria 5 is working according to the way it is written here.

**Comment by fconlon** [comment]
Commit f1bd0c46a69addf78d290a76046bc6e2ec13b643 adds functionality for criteria 5. Closing this issue and opening a bug issue for previously mentioned bug
