### ISSUE TITLE
Open selections in node tree should not be closed on node edits

### ISSUE THREAD

**Issue by fconlon** [opensocsysarch/CoreGenPortal#37]
- [ ] Criteria 1

### Criteria 1
**Given:**
* The node navigation tree has an open selection

**When:**
* The user saves a node edit

**Then:**
* The open selection should remain open

**Comment by jleidel** [comment]
This occurs when the 'Save' button is pressed and handled.  The tree is cleared and reinstantiated.  We need to save off the expanded state if possible.

**Comment by jleidel** [comment]
Saving the wxTreeNodeId and the node pointer then refocusing the text control has proven difficult

**Comment by jleidel** [comment]
passed all devel tests
