### ISSUE TITLE
Complete Inst Edit Window Happy Path 

### ISSUE THREAD

**Issue by fconlon** [opensocsysarch/CoreGenPortal#54]
- [x] Criteria 1
- [x] Criteria 2
- [x] Criteria 3
- [x] Criteria 4
- [x] Criteria 5
- [x] Criteria 6

### Criteria 1
**Given:**
* The Inst edit window is open
* The user has entered a valid name into the Inst Name Box

**When:**
* The user clicks save

**Then:**
* The name of the Inst will be set
* The new name will be saved to the .yaml IR

### Criteria 2
**Given:**
* The Inst edit window is open
* The user has entered a valid Inst Format into  the Inst Format box

**When:**
* The user clicks save

**Then:**
* The Inst Format will be set
* The Inst Format will be saved to the .yaml IR

### Criteria 3
**Given:**
* The Inst edit window is open
* The user has entered a valid Instruction Set into the Instruction Set box

**When:**
* The user clicks save

**Then:**
* The Instruction Set will be set
* The new Instruction Set will be saved to the .yaml IR

### Criteria 4
**Given:**
* The Inst edit window is open
* The user has entered a valid Syntax into the Syntax box

**When:**
* The user clicks save

**Then:**
* The Syntax will be set
* The Syntax will be saved to the .yaml IR

### Criteria 5
**Given:**
* The Inst edit window is open
* The user has entered a valid SC Syntax into the SC Syntax box

**When:**
* The user clicks save

**Then:**
* The Syntax will be set
* The Syntax will be saved to the .yaml IR

### Criteria 6
**Given:**
* The Inst edit window is open
* The user has entered a valid Encoding into the Encodings box

**When:**
* The user clicks save

**Then:**
* The Encoding will be added to the Inst
* The Encoding  will be saved to the .yaml IR

**Comment by fconlon** [comment]
Should encodings be derived from inst format when a new format is added? IE. Why are they cleared when a new inst format is set? It seems like there should be a relationship, but It's implementation isn't readily apparent to me.

**Comment by jleidel** [comment]
Encodings are only derived from the individual instructions for which they are defined.  Encodings won't be tied to an inst format.  Rather, they encode specific data values for a specific field (derived from the format) for a target instruction or pseudo instruction
