### ISSUE TITLE
Complete Inst Edit Window Sad Path

### ISSUE THREAD

**Issue by fconlon** [opensocsysarch/CoreGenPortal#55]
- [x] Criteria 1
- [x] Criteria 2
- [x] Criteria 3
- [x] Criteria 4
- [x] Criteria 5
- [x] Criteria 6

### Criteria 1
**Given:**
* The Inst edit window is open
* The user has entered a invalid name into the Inst Name Box

**When:**
* The user clicks save

**Then:**
* An error message is displayed in the Log Pane
* The Inst Edit window remains open
* The Inst Name label is highlighted red

### Criteria 2
**Given:**
* The Inst edit window is open
* The user has entered an invalid Inst Format into  the Inst Format box

**When:**
* The user clicks save

**Then:**
* An error message is displayed in the Log Pane
* The Inst Edit window remains open
* The Inst Format label is highlighted red

### Criteria 3
**Given:**
* The Inst edit window is open
* The user has entered an invalid Instruction Set into the Instruction Set box

**When:**
* The user clicks save

**Then:**
* An error message is displayed in the Log Pane
* The Inst Edit window remains open
* The Instruction Set label is highlighted red

### Criteria 4
**Given:**
* The Inst edit window is open
* The user has entered an invalid Syntax into the Syntax box

**When:**
* The user clicks save

**Then:**
* An error message is displayed in the Log Pane
* The Inst Edit window remains open
* The Syntax label is highlighted red

### Criteria 5
**Given:**
* The Inst edit window is open
* The user has entered an invalid SC Syntax into the SC Syntax box

**When:**
* The user clicks save

**Then:**
* An error message is displayed in the Log Pane
* The Core Edit window remains open
* The Core Name label is highlighted red

### Criteria 6
**Given:**
* The Inst edit window is open
* The user has entered an invalid Encoding into the Encodings box

**When:**
* The user clicks save

**Then:**
* An error message is displayed in the Log Pane
* The Inst Edit window remains open
* The Encodings label is highlighted red

**Comment by fconlon** [comment]
What constitutes a valid/invalid Syntax/SC Syntax? Do they need validation on this first pass through?

**Comment by jleidel** [comment]
The Syntax structure is defined in Section 2.10 of the CoreGen IR Spec
https://github.com/opensocsysarch/CoreGenIRSpec
`INSTNAME %REGISTER $IMMEDIATE #CONSTANT `

The register and immediate field names must be valid
