### ISSUE TITLE
Reminder to validate Comm endpoints on backend

### ISSUE THREAD

**Issue by fconlon** [opensocsysarch/CoreGenPortal#63]

**Comment by fconlon** [comment]
@jleidel Should I move this over to the backend as an issue there? I remember we discussed this when I was doing the comm edit window, but I don't remember what the reasoning was behind it. I should have left a description of what I meant by "validate"

**Comment by jleidel** [comment]
> @jleidel Should I move this over to the backend as an issue there? I remember we discussed this when I was doing the comm edit window, but I don't remember what the reasoning was behind it. I should have left a description of what I meant by "validate"

Not sure what this is in reference to.  What do you mean "validate".  As long as the InsertEndpoint argument is not NULL or a "CGComm" object, then it should be a valid endpoint.

**Comment by fconlon** [comment]
Oh I think I remember. We were discussing whether or not nodes such as Ext and Plugin nodes should be allowed as endpoints. I think we decided that Ext and Plugin nodes should not be allowed as endpoints. I think IF nodes might also fall under the "it doesn't make sense as an endpoint" category. I should be able to implement this on the front end, but if we wanted to disallow this behavior it would make more sense on the backend. If the verification is only on the front end then it would still be allowed if the user directly used the CLI.

**Comment by jleidel** [comment]
Ext and Plugin nodes should be allowed.  They may encapsulate cores, caches, etc.  However, Inst, PInst and InstFormats should not.  I'll open a bug and make the changes

**Comment by jleidel** [comment]
all the devel tests pass; that bug is now closed

**Comment by fconlon** [comment]
Sounds good I'll close this issue and create one to implement the invalid field highlighting for endpoints in the UI
