### ISSUE TITLE
Complete Register Edit Window Happy Path

### ISSUE THREAD

**Issue by fconlon** [opensocsysarch/CoreGenPortal#65]
- [x] Criteria 1
- [x] Criteria 2
- [x] Criteria 3
- [x] Criteria 4
- [x] Criteria 5
- [x] Criteria 6
- [x] Criteria 7

### Criteria 1
**Given:**
* The Register edit window is open
* The user has entered a valid name into the Register Name Box

**When:**
* The user clicks save

**Then:**
* The name of the Register will be set
* The new name will be saved to the .yaml IR

### Criteria 2
**Given:**
* The Register edit window is open
* The user has entered an integer into the Register Index Box

**When:**
* The user clicks save

**Then:**
* The Register Index will be set
* The new Register Index will be saved to the .yaml IR

### Criteria 3
**Given:**
* The Register edit window is open
* The user has entered an integer into the Register Width Box

**When:**
* The user clicks save

**Then:**
* The register width will be set
* The new register width will be saved to the .yaml IR

### Criteria 4
**Given:**
* The Register edit window is open
* The user has entered a integer into the SIMD Width Box

**When:**
* The user clicks save

**Then:**
* The SIMD width be set
* The register's isSIMD flag will be set to true
* The new SIMD data will be saved to the .yaml IR

### Criteria 5
**Given:**
* The Register edit window is open
* The user has left the SIMD Width Box empty

**When:**
* The user clicks save

**Then:**
* The register's isSIMD flag will be set to false
* The new SIMD data will be saved to the .yaml IR

### Criteria 6
**Given:**
* The Register edit window is open
* The user has entered a valid subregister fields list into the Subregister Fields Box

**When:**
* The user clicks save

**Then:**
* The subregister fields will be added to the Register
* The new subregister fields will be saved to the .yaml IR

### Criteria 7
**Given:**
* The Register edit window is open
* The user has clicked or unclicked a check Box

**When:**
* The user clicks save

**Then:**
* The user's checkbox selections will be set
* The checkbox selections will be saved to the .yaml IR

**Comment by fconlon** [comment]
@jleidel Am I remembering correctly when I remember you saying that register width is derived and I don't need to provide edit functionality for it? There is currently no functionality in the backend to set the register width.

**Comment by jleidel** [comment]
> @jleidel Am I remembering correctly when I remember you saying that register width is derived and I don't need to provide edit functionality for it? There is currently no functionality in the backend to set the register width.

No, register widths are required using the `Width` keyword in the register definition within the Yaml.  You're thinking of the instruction width (which is derived from the associated instruction format)

**Comment by fconlon** [comment]
Follow up question. I don't see a way to unset the isSIMD bool in the register class and the only way to set it to true is SetSIMD(int width). I'm not sure how to handle that on the front end. My first thought is to make it a text box instead of a checkbox and have an empty string set it to false while a non-empty string would set the width. The backend would still need a function to set the isSIMD variable to false though

**Comment by jleidel** [comment]
I can add an interface to unset the SIMD flag.  Your frontend method seems reasonable.

**Comment by jleidel** [comment]
Issue referenced here: https://github.com/opensocsysarch/CoreGen/issues/188

**Comment by jleidel** [comment]
Functionality add here: https://github.com/opensocsysarch/CoreGen/commit/15f997b0878a4fa759db1a0173d4c93ac7ebef48

**Comment by fconlon** [comment]
Awesome. I'm looking at the CoreGenReg code and the PC reg attribute is not being unset in the SetAttrs() function. Is that intentional or is that a bug? 

Edit: I see that it's actually unsetting the mutually exclusive parts of the Attrs int. Could it just set Attrs equal to the new Attrs? I have to run it through gdb to confirm, but I think the unsetting is causing an issue with my attempt to set the RW flag if the user unchecks RO and check RW. I'm not sure if that's the actual issue, but it won't save the flag the first time that they user clicks save, but if they reopen the window and check RW it will save it.

**Comment by fconlon** [comment]
I was able to hack it together by calling unset then set twice back to back, but there may or may not be a bug in the way the attrs are being set on the backend.

**Comment by fconlon** [comment]
@jleidel Is there a reason to return 1 when isSIMD is set to false? The function you wrote that unsets simd sets the SIMDWidth to 0 but the GetSIMDWidth() function returns 1 if isSIMD is set to false.

**Comment by fconlon** [comment]
@jleidel The current version of the SIMD width box will display an empty string if isSIMD is false and will unset isSIMD if 0 or an empty string is entered into the box. However the backend will always return 1 for GetSIMDWidth when isSIMD is false, regardless of  the fact that SIMDWidth is set to 0. I'm going to close this issue since it is working as intended under the current version of the backend. If changes need to be made I will open another issue.

**Comment by jleidel** [comment]
@fconlon, that functionality is correct.  GetSIMDWidth returns 1 when SIMD is disabled.  EG, the register is a scalar register (width = 1).  When width > 1, then the register should be a SIMD register.

**Comment by fconlon** [comment]
That makes sense to me and I figured the initial intent was, but it was confusing that the unset simd set the width to 0. I'll change the UI to set the width accordingly and I'll make an input of 1 unset the simd as well. I'll also populate the box with a 1 instead of an empty string when issimd is false.
